apiVersion: v1
kind: Service
metadata:
  name: fraud-prediction-model-service
spec:
  type: LoadBalancer
  selector:
    app: fraud-prediction-model
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8501